---

# == Notes ==

# - GitLab automatically passes artifacts from previous stages by default
# - Set required secret variables at: https://gitlab.data.bas.ac.uk/web-apps/flask-extensions/flask-azure-oauth/-/settings/ci_cd

# = Secret variables
# - Variables are grouped by section in KEY: "value" format (e.g. FOO: "bar")
#   Sensitive values are represented by "[Sensitive]"
#
# - PyPi (production) - create tokens at https://pypi.org/manage/account/
# > PYPI_TOKEN (protected): "[Sensitive]"
#

# == Global settings ==

stages:
  - 🧪 test
  - 📋 lint
  - 🏗 build
  - 🚚 publish

variables:
  APP_NAME: flask-azure-oauth

image:
  name: docker-registry.data.bas.ac.uk/web-apps/flask-extensions/flask-azure-oauth:latest
  entrypoint: [""]

default:
  before_script:
    - "ln -s /.venv .venv"
    - "poetry install --no-interaction --no-ansi"

# == Jobs ==

test:
  stage: 🧪 test
  needs: []
  variables:
    FLASK_ENV: testing
  before_script:
    - "ln -s /.venv .venv"
    - "poetry install --no-interaction --no-ansi"
    - "cp support/python-tests-junit/tests.py ./"
  script:
    - "poetry run python ./tests.py"
  artifacts:
    reports:
      junit: test-results.xml
    expire_in: 1 month
  rules:
    - changes:
        - '**/*.py'

lint:
  stage: 📋 lint
  needs: []
  script:
    - "poetry check"
    - "poetry run flake8 src/ examples/"
    - "poetry export --without-hashes -f requirements.txt | poetry run safety check --full-report --stdin"
  rules:
    - changes:
        - '**/*.py'

build:
  stage: 🏗 build
  needs: []
  script:
    - "poetry version 0.0.0"
    - "poetry build"
  artifacts:
    paths:
      - dist
    expire_in: 1 week
  rules:
    -
      if: '$CI_COMMIT_TAG == null'
      changes:
        - '**/*.py'

publish:
  stage: 🚚 publish
  needs:
    - test
    - lint
  before_script:
    - "ln -s /.venv .venv"
    - "poetry install --no-interaction --no-ansi"
    - "poetry config pypi-token.pypi $PYPI_TOKEN --local"
  script:
    - "poetry publish --build --no-interaction"
  artifacts:
    paths:
      - dist
    expire_in: 1 month
  rules:
    - if: '$CI_COMMIT_TAG != null'
  environment:
    name: production
    url: https://pypi.org/project/flask-azure-oauth/
