[tool.poetry]
name = "flask-azure"
version = "0.1.0"
description = "Experiment to update how access to a Flask app can be controlled using Azure/Entra ID."
authors = ["Felix Fennell <felnne@bas.ac.uk>"]
readme = "README.md"
license = "MIT"
packages = [{include = "flask_azure", from = "src"}]

[tool.poetry.dependencies]
python = "^3.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
